version: '3.7'

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "6597:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    build:
      context: docker/wordpress
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
#      - wp_data:/var/www/html
      - ./src:/var/www/html
      - ./coldbox-addon:/var/www/html/coldbox-addon
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
    ports:
      - "6507:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  cli:
    image: wordpress:cli
    user: xfs
    volumes:
#      - wp_data:/var/www/html
      - ./src:/var/www/html
    depends_on:
      - wordpress
      - db

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "6525:1025"
      - "6580:1080"

volumes:
  db_data:
  wp_data:
